import uuid
from google.adk.tools import FunctionTool
# We no longer need to import the enums here
from app.schemas.ticket_state import TicketState

def create_structured_ticket(ticket: TicketState) -> TicketState:
    """
    Accepts a structured TicketState object generated by the LLM, assigns
    a unique ticket_id, and returns the completed ticket.
    
    Args:
        ticket: A TicketState object populated by the LLM.
    """
    print("✅ Tool 'create_structured_ticket' was called successfully.")
    
    # Assign a unique ID to the ticket object we received from the LLM.
    ticket.ticket_id = str(uuid.uuid4())
    
    print(f"   - Assigned new Ticket ID: {ticket.ticket_id}")
    
    # Return the modified ticket object. This will become the session state.
    return ticket

# Rename the tool object for clarity.
create_structured_ticket_tool = FunctionTool(create_structured_ticket)